import type { CharacterProfile } from "./characterProfile.js";

/**
 * The 9 character profiles from character-ai-spec.txt, registered verbatim. Do not alter
 * these values without explicit instruction - see the spec's own note: "Do not automatically
 * retune parameter values without explicit instruction."
 */
export const CHARACTER_PROFILES: Record<string, CharacterProfile> = {
  jegalmina: {
    characterId: "jegalmina",
    displayName: "제갈 미나",
    archetype: "high_skill_stochastic",
    skill: 0.86,
    aggression: 0.57,
    defense: 0.54,
    riichiBias: 0.47,
    damaBias: 0.61,
    callBias: 0.29,
    foldThreshold: 0.46,
    valueGreed: 0.7,
    honitsuBias: 0.31,
    chiitoitsuBias: 0.59,
    yakumanGreed: 0.57,
    riskTolerance: 0.6,
    entropy: 0.78,
    mistakeRate: 0.015,
    candidateScoreTolerance: 0.06,
  },
  jegalnahui: {
    characterId: "jegalnahui",
    displayName: "제갈 나희",
    archetype: "high_speed_table_reader",
    skill: 0.84,
    aggression: 0.66,
    defense: 0.69,
    riichiBias: 0.67,
    damaBias: 0.38,
    callBias: 0.47,
    foldThreshold: 0.52,
    valueGreed: 0.43,
    honitsuBias: 0.27,
    chiitoitsuBias: 0.32,
    yakumanGreed: 0.31,
    riskTolerance: 0.64,
    entropy: 0.22,
    mistakeRate: 0.008,
    candidateScoreTolerance: 0.035,
    overloadSensitivity: 0.72,
    overloadErrorSeverity: 0.12,
  },
  seiyamouri: {
    characterId: "seiyamouri",
    displayName: "세이야 모우리",
    archetype: "aggressive_tempo_feeder",
    skill: 0.61,
    aggression: 0.8,
    defense: 0.35,
    riichiBias: 0.72,
    damaBias: 0.22,
    callBias: 0.78,
    foldThreshold: 0.28,
    valueGreed: 0.42,
    honitsuBias: 0.34,
    chiitoitsuBias: 0.23,
    yakumanGreed: 0.43,
    riskTolerance: 0.78,
    entropy: 0.57,
    mistakeRate: 0.025,
    candidateScoreTolerance: 0.075,
  },
  seiyakouri: {
    characterId: "seiyakouri",
    displayName: "세이야 코우리",
    archetype: "control_oriented_closed_player",
    skill: 0.7,
    aggression: 0.49,
    defense: 0.72,
    riichiBias: 0.38,
    damaBias: 0.72,
    callBias: 0.26,
    foldThreshold: 0.67,
    valueGreed: 0.66,
    honitsuBias: 0.49,
    chiitoitsuBias: 0.52,
    yakumanGreed: 0.46,
    riskTolerance: 0.39,
    entropy: 0.19,
    mistakeRate: 0.01,
    candidateScoreTolerance: 0.035,
  },
  kyletyler: {
    characterId: "kyletyler",
    displayName: "카일 타일러",
    archetype: "novice_experimentalist",
    skill: 0.36,
    aggression: 0.54,
    defense: 0.27,
    riichiBias: 0.43,
    damaBias: 0.28,
    callBias: 0.39,
    foldThreshold: 0.24,
    valueGreed: 0.76,
    honitsuBias: 0.58,
    chiitoitsuBias: 0.63,
    yakumanGreed: 0.79,
    riskTolerance: 0.67,
    entropy: 0.61,
    mistakeRate: 0.065,
    candidateScoreTolerance: 0.1,
    experimentBias: 0.84,
    routePersistence: 0.76,
  },
  seiyatosuke: {
    characterId: "seiyatosuke",
    displayName: "세이야 토스케",
    archetype: "expert_sandbagger",
    skill: 0.96,
    aggression: 0.44,
    defense: 0.88,
    riichiBias: 0.4,
    damaBias: 0.74,
    callBias: 0.21,
    foldThreshold: 0.76,
    valueGreed: 0.63,
    honitsuBias: 0.37,
    chiitoitsuBias: 0.49,
    yakumanGreed: 0.41,
    riskTolerance: 0.31,
    entropy: 0.12,
    mistakeRate: 0.003,
    candidateScoreTolerance: 0.02,
    sandbagging: 0.72,
    interventionThreshold: 0.82,
  },
  toumesuashi: {
    characterId: "toumesuashi",
    displayName: "토우메 스아시",
    archetype: "cautious_deep_planner",
    skill: 0.89,
    aggression: 0.42,
    defense: 0.81,
    riichiBias: 0.41,
    damaBias: 0.68,
    callBias: 0.23,
    foldThreshold: 0.73,
    valueGreed: 0.62,
    honitsuBias: 0.36,
    chiitoitsuBias: 0.48,
    yakumanGreed: 0.35,
    riskTolerance: 0.3,
    entropy: 0.13,
    mistakeRate: 0.005,
    candidateScoreTolerance: 0.025,
  },
  toumesuayo: {
    characterId: "toumesuayo",
    displayName: "토우메 스아요",
    archetype: "straightforward_risk_taker",
    skill: 0.52,
    aggression: 0.64,
    defense: 0.39,
    riichiBias: 0.68,
    damaBias: 0.2,
    callBias: 0.55,
    foldThreshold: 0.33,
    valueGreed: 0.35,
    honitsuBias: 0.32,
    chiitoitsuBias: 0.27,
    yakumanGreed: 0.34,
    riskTolerance: 0.67,
    entropy: 0.45,
    mistakeRate: 0.032,
    candidateScoreTolerance: 0.075,
  },
  byeonari: {
    characterId: "byeonari",
    displayName: "변아리",
    archetype: "clean_control_player",
    skill: 0.68,
    aggression: 0.48,
    defense: 0.76,
    riichiBias: 0.46,
    damaBias: 0.58,
    callBias: 0.24,
    foldThreshold: 0.7,
    valueGreed: 0.56,
    honitsuBias: 0.44,
    chiitoitsuBias: 0.31,
    yakumanGreed: 0.29,
    riskTolerance: 0.32,
    entropy: 0.16,
    mistakeRate: 0.012,
    candidateScoreTolerance: 0.03,
    shapeCleanlinessBias: 0.78,
    contaminationAversion: 0.74,
  },
  // Student profiles (character-ai-spec-complete.txt STUDENT PROFILES section). None of
  // these declare any of the four special-mechanic fields - per that spec's own
  // IMPLEMENTATION NOTES, only jegalnahui/kyletyler/seiyatosuke/byeonari get bespoke
  // mechanics; every other profile is expressed entirely through the shared parameters.
  kangunsim: {
    characterId: "kangunsim",
    displayName: "강운심",
    archetype: "fast_tempo_information_chaser",
    skill: 0.76,
    aggression: 0.7,
    defense: 0.51,
    riichiBias: 0.61,
    damaBias: 0.29,
    callBias: 0.64,
    foldThreshold: 0.38,
    valueGreed: 0.3,
    honitsuBias: 0.3,
    chiitoitsuBias: 0.25,
    yakumanGreed: 0.35,
    riskTolerance: 0.64,
    entropy: 0.43,
    mistakeRate: 0.02,
    candidateScoreTolerance: 0.065,
  },
  kimwooju: {
    characterId: "kimwooju",
    displayName: "김우주",
    archetype: "threat_aware_operator",
    skill: 0.87,
    aggression: 0.38,
    defense: 0.86,
    riichiBias: 0.47,
    damaBias: 0.7,
    callBias: 0.21,
    foldThreshold: 0.81,
    valueGreed: 0.49,
    honitsuBias: 0.28,
    chiitoitsuBias: 0.41,
    yakumanGreed: 0.22,
    riskTolerance: 0.24,
    entropy: 0.18,
    mistakeRate: 0.006,
    candidateScoreTolerance: 0.025,
  },
  ryumint: {
    characterId: "ryumint",
    displayName: "류민트",
    archetype: "reckless_direct_brawler",
    skill: 0.48,
    aggression: 0.82,
    defense: 0.29,
    riichiBias: 0.62,
    damaBias: 0.18,
    callBias: 0.72,
    foldThreshold: 0.24,
    valueGreed: 0.31,
    honitsuBias: 0.33,
    chiitoitsuBias: 0.2,
    yakumanGreed: 0.39,
    riskTolerance: 0.84,
    entropy: 0.55,
    mistakeRate: 0.042,
    candidateScoreTolerance: 0.085,
  },
  inan: {
    characterId: "inan",
    displayName: "이난",
    archetype: "temperate_table_stabilizer",
    skill: 0.74,
    aggression: 0.37,
    defense: 0.8,
    riichiBias: 0.39,
    damaBias: 0.66,
    callBias: 0.25,
    foldThreshold: 0.72,
    valueGreed: 0.47,
    honitsuBias: 0.3,
    chiitoitsuBias: 0.4,
    yakumanGreed: 0.24,
    riskTolerance: 0.27,
    entropy: 0.17,
    mistakeRate: 0.011,
    candidateScoreTolerance: 0.03,
  },
  effieminos: {
    characterId: "effieminos",
    displayName: "에피 미노스",
    archetype: "value_hoarding_collector",
    skill: 0.62,
    aggression: 0.46,
    defense: 0.5,
    riichiBias: 0.4,
    damaBias: 0.56,
    callBias: 0.3,
    foldThreshold: 0.45,
    valueGreed: 0.84,
    honitsuBias: 0.61,
    chiitoitsuBias: 0.72,
    yakumanGreed: 0.66,
    riskTolerance: 0.46,
    entropy: 0.38,
    mistakeRate: 0.024,
    candidateScoreTolerance: 0.065,
    attachmentBias: 0.68,
    attachmentReleaseThreshold: 0.6,
  },
  hwayoung: {
    characterId: "hwayoung",
    displayName: "화영",
    archetype: "competitive_endurance_pusher",
    skill: 0.65,
    aggression: 0.72,
    defense: 0.53,
    riichiBias: 0.64,
    damaBias: 0.31,
    callBias: 0.48,
    foldThreshold: 0.39,
    valueGreed: 0.55,
    honitsuBias: 0.35,
    chiitoitsuBias: 0.29,
    yakumanGreed: 0.42,
    riskTolerance: 0.72,
    entropy: 0.31,
    mistakeRate: 0.022,
    candidateScoreTolerance: 0.06,
  },
  mageuna: {
    characterId: "mageuna",
    displayName: "마근아",
    archetype: "rule_bound_planner",
    skill: 0.72,
    aggression: 0.5,
    defense: 0.73,
    riichiBias: 0.55,
    damaBias: 0.54,
    callBias: 0.27,
    foldThreshold: 0.66,
    valueGreed: 0.58,
    honitsuBias: 0.29,
    chiitoitsuBias: 0.42,
    yakumanGreed: 0.25,
    riskTolerance: 0.34,
    entropy: 0.11,
    mistakeRate: 0.024,
    candidateScoreTolerance: 0.03,
    planPersistence: 0.74,
    disruptionInstability: 0.62,
  },
  magnum: {
    characterId: "magnum",
    displayName: "매그넘",
    archetype: "novelty_seeking_opportunist",
    skill: 0.6,
    aggression: 0.8,
    defense: 0.28,
    riichiBias: 0.69,
    damaBias: 0.2,
    callBias: 0.69,
    foldThreshold: 0.25,
    valueGreed: 0.71,
    honitsuBias: 0.53,
    chiitoitsuBias: 0.5,
    yakumanGreed: 0.8,
    riskTolerance: 0.83,
    entropy: 0.84,
    mistakeRate: 0.04,
    candidateScoreTolerance: 0.09,
  },
  optima215: {
    characterId: "optima215",
    displayName: "옵티마-215",
    archetype: "literal_threshold_reasoner",
    skill: 0.59,
    aggression: 0.5,
    defense: 0.55,
    riichiBias: 0.63,
    damaBias: 0.28,
    callBias: 0.38,
    foldThreshold: 0.5,
    valueGreed: 0.36,
    honitsuBias: 0.25,
    chiitoitsuBias: 0.33,
    yakumanGreed: 0.21,
    riskTolerance: 0.47,
    entropy: 0.7,
    mistakeRate: 0.018,
    candidateScoreTolerance: 0.075,
    binaryConfidence: 0.86,
    ambiguitySensitivity: 0.82,
  },
  yuwen: {
    characterId: "yuwen",
    displayName: "여온",
    archetype: "easygoing_intuitive_responder",
    skill: 0.47,
    aggression: 0.42,
    defense: 0.49,
    riichiBias: 0.52,
    damaBias: 0.3,
    callBias: 0.45,
    foldThreshold: 0.46,
    valueGreed: 0.31,
    honitsuBias: 0.24,
    chiitoitsuBias: 0.29,
    yakumanGreed: 0.18,
    riskTolerance: 0.48,
    entropy: 0.48,
    mistakeRate: 0.034,
    candidateScoreTolerance: 0.075,
  },
  josangmin: {
    characterId: "josangmin",
    displayName: "조상민",
    archetype: "minimal_action_optimizer",
    skill: 0.79,
    aggression: 0.35,
    defense: 0.8,
    riichiBias: 0.39,
    damaBias: 0.73,
    callBias: 0.16,
    foldThreshold: 0.76,
    valueGreed: 0.45,
    honitsuBias: 0.24,
    chiitoitsuBias: 0.38,
    yakumanGreed: 0.17,
    riskTolerance: 0.24,
    entropy: 0.08,
    mistakeRate: 0.007,
    candidateScoreTolerance: 0.02,
    effortAversion: 0.72,
    commitmentAversion: 0.76,
  },
  seiyahikudo: {
    characterId: "seiyahikudo",
    displayName: "세이야 히쿠도",
    archetype: "high_value_showman",
    skill: 0.82,
    aggression: 0.7,
    defense: 0.5,
    riichiBias: 0.84,
    damaBias: 0.18,
    callBias: 0.33,
    foldThreshold: 0.36,
    valueGreed: 0.82,
    honitsuBias: 0.56,
    chiitoitsuBias: 0.44,
    yakumanGreed: 0.76,
    riskTolerance: 0.68,
    entropy: 0.36,
    mistakeRate: 0.017,
    candidateScoreTolerance: 0.05,
  },
  ryuhart: {
    characterId: "ryuhart",
    displayName: "류하트",
    archetype: "rough_shape_fast_completer",
    skill: 0.45,
    aggression: 0.52,
    defense: 0.44,
    riichiBias: 0.49,
    damaBias: 0.24,
    callBias: 0.61,
    foldThreshold: 0.4,
    valueGreed: 0.22,
    honitsuBias: 0.23,
    chiitoitsuBias: 0.34,
    yakumanGreed: 0.16,
    riskTolerance: 0.57,
    entropy: 0.53,
    mistakeRate: 0.039,
    candidateScoreTolerance: 0.085,
  },
};

export function getCharacterProfile(characterId: string): CharacterProfile {
  const profile = CHARACTER_PROFILES[characterId];
  if (!profile) throw new Error(`Unknown character id: ${characterId}`);
  return profile;
}
